# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' check_file, check is file path are correct
#'
#' @param files a vector of bed files path
#'
#' @return
#' save a list of preprocessed bed files 
#' @export
#'
check_files <- function(files) {
  for (file in files) {
    if (!file.exists(file)) {
      stop(
        paste(
          file,
          " does not exist in current working directory ('",
          getwd(), "')."
        )
      )
    }
  }
}
