# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' compute_hawkes_histogram
#'
#' @param files a vector of bed files path
#' @param names (default: files) names of the samples
#' @param K (default: 10) size of the histogram bins
#' @param delta (default: 1e4) max range to consider
#' @param kernel (default: "heterogeneous_interval") kernel for the computation
#'
#' @return
#' save a results file
#' @export
#'
compute_hawkes_histogram <- function(
    files, names = files, K = 10, delta = 1e4,
  kernel = "heterogeneous_interval") {
  cmd <- c()
  for (bed in files) {
    cmd <- c(cmd, paste("-b", bed))
  }
  cmd <- c(cmd, paste("-histogram", K, delta))
  cmd <- c(cmd, paste("-kernel", kernel))
  cmd <- c(cmd, "-lambda 1")
  system2(
    "src/hawkes_bin",
    cmd,
    stdout = TRUE
  ) |>
  textConnection() |>
  read.table(col.names = names) |>
  as.matrix()
}

