# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' hw convolution of the h interaction function with the kernel of the 2
#' processus
#'
#' @param data results of compute_hawkes_histogram
#' @param width a vector of beds interval width (in the same orde as the data columns)
#' @param K (default: 10) size of the histogram bins
#' @param delta (default: 1e4) max range to consider
#' 
#' @return
#' tibble
#' @export
#'
#' @importFrom dplyr group_by mutate select
#' @importFrom purrr map_dbl map2 map
#' @importFrom tidyr nest unnest
convolve_with_kernel <- function(data, width, K = 10, delta = 1e4) {
  getparam(data, K = K, delta = delta) |> 
  dplyr::group_by(name, vs_name) |>
  dplyr::mutate(
    width = purrr::map_dbl(name, function(x, width = width, names = names) {
        width[which(names == x)]
      }, width = width, names = colnames(data)
    ),
    vs_width = purrr::map_dbl(
        vs_name, function(x, width = width, names = names) {
        width[which(names == x)]
      }, width = width, names = colnames(data)
    )
    
  ) |> 
  dplyr::group_by(name, vs_name) |>
  tidyr::nest(params = c(value, width, vs_width, start, stop)) |>
  dplyr::mutate(
    convolution = purrr::map(
      params,
      function(params, delta = delta, K = K) {
         params |>
          dplyr::mutate(
            position = purrr::map2(
              start, stop, function(x, y) {
                x:y
              })
          ) |>
          tidyr::unnest(c(position)) |>
          dplyr::mutate(
            convolution = triple_convolution(
                position, value, width, vs_width, delta
            )
          ) |>
        dplyr::select(c(position, convolution)) |>
        dplyr::mutate(
          position = position - max(position) / 2,
        )
      }, delta = delta, K = K
    )
  )
}

