# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' helper function for preprocess_bed to compute a sliding windows along all
#' the beds and filter out position present in only one beds file
#'
#' @param data a tibble
#' @param maxlag the size of the windows
#'
#' @return
#' tibble
#' @importFrom dplyr group_by arrange mutate filter
#' @importFrom tidyr nest
#' @noRd
filter_windows <- function(data, maxlag) {
  data |> 
    dplyr::group_by(chr) |>
    dplyr::arrange(start, stop, .by_group = TRUE) |>
    dplyr::mutate(
      window = purrr::pmap_int(
        list(names, start, stop), function(names, start, stop, max_lag) {
          min(start) %/% max_lag + 1
        }, max_lag = maxlag)
    ) |> 
    dplyr::group_by(chr, window) |>
    dplyr::mutate(
      count = length(levels(as.factor(names))),
    ) |> 
    dplyr::filter(count > 1) |>
    dplyr::group_by(files) |>
    dplyr::select(files, names, chr, start, stop) |>
    dplyr::mutate(
      interval_size = mean(stop - start)
    ) |> 
    tidyr::nest(beds = c(chr, start, stop))
}
