# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' getparam
#'
#' @param data a matrix of parameters 
#' @param K (default: 10) size of the histogram bins
#' @param delta (default: 1e4) max range to consider
#' @return
#' Median of vector x
#' @export
#'
#' @importFrom tibble as_tibble
#' @importFrom dplyr slice mutate relocate arrange n
#' @importFrom tidyr pivot_longer
getparam <- function(data, K = 10, delta = 1e4) {
  res |> 
    tibble::as_tibble() |>
    dplyr::slice(2:n()) |>
    dplyr::mutate(
      vs_name = rep(1:ncol(res), each = K),
      start = rep(rep(0:(K - 1)), ncol(res)) * delta * 2 + 1,
      stop = rep(rep(1:K), ncol(res)) * delta * 2
    ) |>
    dplyr::mutate(
      vs_name = levels(as.factor(colnames(res)))[vs_name],
    ) |>
    tidyr::pivot_longer(cols = !c(vs_name, start, stop)) |>
    dplyr::relocate(name) |>
    dplyr::arrange(name, vs_name, start, stop)
  
}
