# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' preprocess_bed preprocess bed file to remove windows of size maxlag for chich
#' there is no signal or only signal in one sample
#'
#' @param files a vector of bed files path
#' @param names (default: files) a list of names for the sample
#' @param maxlag (default: 1e5) the size of the windows
#' @param prefix (default: "clean_") the prefix of the preprocessed bed file
#' @param outdir (default: "tempdir()") path for the preprocessed bed files
#'
#' @return
#' save a list of preprocessed bed files 
#' @export
#'
#' @importFrom tibble tibble
#' @importFrom dplyr mutate 
#' @importFrom purrr map map2
#' @importFrom tidyr unnest
preprocess_bed <- function(
  files, names = files, maxlag = 1e5, prefix = "", outdir = tempdir()) {
  tibble::tibble(
    files = files,
    names = names
  ) |> 
    dplyr::mutate(
      bed = purrr::map(files, read_bed)
    ) |>
  tidyr::unnest(cols = c(bed)) |>
  filter_windows(maxlag = maxlag) |>
  dplyr::mutate(
    preprocess_beds = purrr::map2(
        files, beds, write_bed, outdir = outdir, prefix = prefix)
  ) |>
  tidyr::unnest(preprocess_beds)
}
