# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' the uniform kernel of width width 
#'
#' @param position position on which to convolve
#' @param x interaction function parameter
#' @param width width of the uniform kernel for the first process
#' @param vs_width width of the uniform kernel for the second process 
#' @param delta (default: 1e4) max range to consider
#'
#' @return
#' Median of vector x
#' @export
#'
triple_convolution <- function(position, x, width, vs_width, delta = 1e4) {
  (x / sqrt(delta)) |>
    convolve(uniform_kernel(position, width)) |>
    convolve(uniform_kernel(position, vs_width))
}
