# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' the uniform kernel of width width 
#'
#' @param x vector of data
#' @param width width of the uniform kernel
#'
#' @return
#' Median of vector x
#' @export
#'
uniform_kernel <- function(x, width){
  1 * (abs(x) <= width) / width
}
