# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' helper function for preprocess_bed to write bed files
#'
#' @param path a bed file path
#' @param data a tibble of bed information
#' @param outdir the path were to write the results
#' @param prefix (default: "clean_") the prefix of the preprocessed bed file
#'
#' @return
#' a path
#' @importFrom stringr str_split str_c
#' @importFrom vroom vroom_write
#' @noRd
write_bed <- function(path, data, outdir, prefix = "clean_") {
  path <- stringr::str_split(path, "/")[[1]]
  path <- stringr::str_c(outdir, "/", prefix, path[length(path)])
  vroom::vroom_write(
    data,
    file = path,
    delim = "\t",
    col_names = FALSE,
    quote = "none"
  )
  return(path)
}
